stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw/
  
  preprocessing:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/
    outs:
      - data/interim/
  
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/interim/
    params:
      - feature_engineering.max_features
    outs:
      - data/processed/
  
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/processed/
    params:
      - model_training.n_estimators
      - model_training.random_state
    outs:
      - models/model.pkl
  
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/processed/
    params:
      - model_training.n_estimators
      - model_training.random_state
    outs:
      - reports/metrics.json